# Example configuration for the benchmark analysis tool
# This file shows all available options and their usage

data:
  # First data group - RHOAI platform results
  #- extra_metadata:
  #    platform: RHOAI
  #    GPU: H100
  #    GPU_count: 16
  #    notes: "Production RHOAI environment"
  #  files:
  #    - "../results/RHOAI/*-1000-1000-sweep.json"
  #    - "../results/RHOAI/*-2000-1000-sweep.json"  # Add more patterns as needed
  
  # Second data group - llm-d platform results
  - extra_metadata:
      platform: llm-d
      GPU: H100
      GPU_count: 16  
      notes: "Development llm-d environment"
    files:
      - ../results/llm-d-0.2.0-kvcache-precise/20250806-173540-r8-1000-1000-sweep.json

options:
  # Column to use for grouping/coloring charts
  # Common options: 'platform', 'dataset_id', 'GPU', or any extra_metadata field
  color: platform
  
  # X-axis mode: 'concurrency' or 'rps' 
  # Determines whether charts show concurrency levels or RPS levels on x-axis
  axis_mode: concurrency
  
  # Optional: Filter to specific concurrency levels (for axis_mode: concurrency)
  # If not specified, all available levels are used
  concurrency_levels: [1, 50, 75, 100, 125, 150, 200, 300, 400, 500, 600, 800, 1000, 1200]
  
  # Optional: Filter to specific RPS levels (for axis_mode: rps)
  # Use this instead of concurrency_levels when axis_mode is 'rps'
  # rps_levels: [10, 25, 50, 100, 200, 500]

